name: "✨ Feature request"
description: "Create a new feature or enhancement request"
title: "[FEAT]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please make sure this feature request hasn't been already submitted by someone by looking through other open/closed issues
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a brief description of the proposed feature or enhancement
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Provide some additional information on the feature request: e.g. proposed solutions, links, screenshots, etc.
